# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lms.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LibraryUI(object):
    def setupUi(self, LibraryUI):
        LibraryUI.setObjectName(_fromUtf8("LibraryUI"))
        LibraryUI.resize(798, 600)
        self.centralwidget = QtGui.QWidget(LibraryUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.bsButton = QtGui.QPushButton(self.tab_1)
        self.bsButton.setGeometry(QtCore.QRect(460, 30, 111, 31))
        self.bsButton.setObjectName(_fromUtf8("bsButton"))
        self.bktableWidget = QtGui.QTableWidget(self.tab_1)
        self.bktableWidget.setGeometry(QtCore.QRect(20, 80, 711, 391))
        self.bktableWidget.setObjectName(_fromUtf8("bktableWidget"))
        self.bktableWidget.setColumnCount(0)
        self.bktableWidget.setRowCount(0)
        self.bsEdit = QtGui.QTextEdit(self.tab_1)
        self.bsEdit.setGeometry(QtCore.QRect(20, 30, 431, 31))
        self.bsEdit.setObjectName(_fromUtf8("bsEdit"))
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.coutIDlineEdit = QtGui.QLineEdit(self.tab_2)
        self.coutIDlineEdit.setGeometry(QtCore.QRect(120, 60, 113, 27))
        self.coutIDlineEdit.setObjectName(_fromUtf8("coutIDlineEdit"))
        self.coutISBNlineEdit = QtGui.QLineEdit(self.tab_2)
        self.coutISBNlineEdit.setGeometry(QtCore.QRect(120, 110, 113, 27))
        self.coutISBNlineEdit.setObjectName(_fromUtf8("coutISBNlineEdit"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(40, 60, 68, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(50, 110, 51, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.coutdoButton = QtGui.QPushButton(self.tab_2)
        self.coutdoButton.setGeometry(QtCore.QRect(30, 160, 201, 27))
        self.coutdoButton.setObjectName(_fromUtf8("coutdoButton"))
        self.coutmessagetextEdit = QtGui.QTextEdit(self.tab_2)
        self.coutmessagetextEdit.setGeometry(QtCore.QRect(20, 360, 231, 81))
        self.coutmessagetextEdit.setObjectName(_fromUtf8("coutmessagetextEdit"))
        self.coutclearButton = QtGui.QPushButton(self.tab_2)
        self.coutclearButton.setGeometry(QtCore.QRect(640, 460, 121, 27))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.coutclearButton.setFont(font)
        self.coutclearButton.setObjectName(_fromUtf8("coutclearButton"))
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(100, 340, 68, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(280, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.loanSearchlineEdit = QtGui.QLineEdit(self.tab_2)
        self.loanSearchlineEdit.setGeometry(QtCore.QRect(300, 60, 331, 27))
        self.loanSearchlineEdit.setObjectName(_fromUtf8("loanSearchlineEdit"))
        self.loanSearchButton = QtGui.QPushButton(self.tab_2)
        self.loanSearchButton.setGeometry(QtCore.QRect(640, 60, 99, 27))
        self.loanSearchButton.setObjectName(_fromUtf8("loanSearchButton"))
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(20, 220, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(40, 250, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.checkInButton = QtGui.QPushButton(self.tab_2)
        self.checkInButton.setGeometry(QtCore.QRect(30, 280, 201, 27))
        self.checkInButton.setObjectName(_fromUtf8("checkInButton"))
        self.loanSearchtableWidget = QtGui.QTableWidget(self.tab_2)
        self.loanSearchtableWidget.setGeometry(QtCore.QRect(300, 100, 471, 351))
        self.loanSearchtableWidget.setObjectName(_fromUtf8("loanSearchtableWidget"))
        self.loanSearchtableWidget.setColumnCount(0)
        self.loanSearchtableWidget.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.label = QtGui.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(40, 30, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.ssn_in = QtGui.QTextEdit(self.tab_3)
        self.ssn_in.setGeometry(QtCore.QRect(200, 80, 171, 31))
        self.ssn_in.setObjectName(_fromUtf8("ssn_in"))
        self.name_in = QtGui.QTextEdit(self.tab_3)
        self.name_in.setGeometry(QtCore.QRect(200, 130, 281, 31))
        self.name_in.setObjectName(_fromUtf8("name_in"))
        self.address_in = QtGui.QTextEdit(self.tab_3)
        self.address_in.setGeometry(QtCore.QRect(200, 180, 401, 31))
        self.address_in.setObjectName(_fromUtf8("address_in"))
        self.phone_in = QtGui.QTextEdit(self.tab_3)
        self.phone_in.setGeometry(QtCore.QRect(310, 230, 171, 31))
        self.phone_in.setObjectName(_fromUtf8("phone_in"))
        self.label_2 = QtGui.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 101, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(70, 140, 68, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(70, 190, 71, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(70, 240, 221, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(70, 290, 101, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.id_out = QtGui.QTextEdit(self.tab_3)
        self.id_out.setGeometry(QtCore.QRect(200, 280, 101, 31))
        self.id_out.setObjectName(_fromUtf8("id_out"))
        self.createNewBorrowerButton = QtGui.QPushButton(self.tab_3)
        self.createNewBorrowerButton.setGeometry(QtCore.QRect(70, 350, 99, 27))
        self.createNewBorrowerButton.setObjectName(_fromUtf8("createNewBorrowerButton"))
        self.clearInfoButtonTab3 = QtGui.QPushButton(self.tab_3)
        self.clearInfoButtonTab3.setGeometry(QtCore.QRect(70, 400, 99, 27))
        self.clearInfoButtonTab3.setObjectName(_fromUtf8("clearInfoButtonTab3"))
        self.message_box = QtGui.QTextEdit(self.tab_3)
        self.message_box.setGeometry(QtCore.QRect(230, 380, 161, 101))
        self.message_box.setObjectName(_fromUtf8("message_box"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(280, 360, 68, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_15 = QtGui.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(620, 50, 68, 17))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setUnderline(False)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.finetextEdit = QtGui.QTextEdit(self.tab_4)
        self.finetextEdit.setGeometry(QtCore.QRect(550, 70, 211, 121))
        self.finetextEdit.setObjectName(_fromUtf8("finetextEdit"))
        self.finetableWidget = QtGui.QTableWidget(self.tab_4)
        self.finetableWidget.setGeometry(QtCore.QRect(20, 70, 521, 381))
        self.finetableWidget.setObjectName(_fromUtf8("finetableWidget"))
        self.finetableWidget.setColumnCount(0)
        self.finetableWidget.setRowCount(0)
        self.finelineEdit = QtGui.QLineEdit(self.tab_4)
        self.finelineEdit.setGeometry(QtCore.QRect(20, 30, 291, 31))
        self.finelineEdit.setObjectName(_fromUtf8("finelineEdit"))
        self.fineinfoupdateButton = QtGui.QPushButton(self.tab_4)
        self.fineinfoupdateButton.setGeometry(QtCore.QRect(310, 30, 121, 31))
        self.fineinfoupdateButton.setObjectName(_fromUtf8("fineinfoupdateButton"))
        self.fineclearButton = QtGui.QPushButton(self.tab_4)
        self.fineclearButton.setGeometry(QtCore.QRect(430, 30, 111, 31))
        self.fineclearButton.setObjectName(_fromUtf8("fineclearButton"))
        self.label_16 = QtGui.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(550, 210, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(550, 230, 211, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.finepayButton = QtGui.QPushButton(self.tab_4)
        self.finepayButton.setGeometry(QtCore.QRect(550, 250, 211, 31))
        self.finepayButton.setObjectName(_fromUtf8("finepayButton"))
        self.label_18 = QtGui.QLabel(self.tab_4)
        self.label_18.setGeometry(QtCore.QRect(550, 290, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        LibraryUI.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(LibraryUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        LibraryUI.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(LibraryUI)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        LibraryUI.setStatusBar(self.statusbar)

        self.retranslateUi(LibraryUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LibraryUI)

    def retranslateUi(self, LibraryUI):
        LibraryUI.setWindowTitle(_translate("LibraryUI", "Library Management System", None))
        self.bsButton.setText(_translate("LibraryUI", "Search", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("LibraryUI", "Book Search", None))
        self.label_8.setText(_translate("LibraryUI", "Check Out :", None))
        self.label_9.setText(_translate("LibraryUI", "Card ID :", None))
        self.label_10.setText(_translate("LibraryUI", "ISBN :", None))
        self.coutdoButton.setText(_translate("LibraryUI", "Check Out", None))
        self.coutclearButton.setText(_translate("LibraryUI", "Clear", None))
        self.label_11.setText(_translate("LibraryUI", "Message:", None))
        self.label_12.setText(_translate("LibraryUI", "Loan Search:", None))
        self.loanSearchButton.setText(_translate("LibraryUI", "Search", None))
        self.label_13.setText(_translate("LibraryUI", "Check In:", None))
        self.label_14.setText(_translate("LibraryUI", "select rows, and press Check In", None))
        self.checkInButton.setText(_translate("LibraryUI", "Check In", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("LibraryUI", "Book Loans", None))
        self.label.setText(_translate("LibraryUI", "Add New Borrower:", None))
        self.label_2.setText(_translate("LibraryUI", "SSN (9 digits) :", None))
        self.label_3.setText(_translate("LibraryUI", "Name :", None))
        self.label_4.setText(_translate("LibraryUI", "Address :", None))
        self.label_5.setText(_translate("LibraryUI", "Phone (10 digits, not required) :", None))
        self.label_6.setText(_translate("LibraryUI", "Generated ID :", None))
        self.createNewBorrowerButton.setText(_translate("LibraryUI", "Create !", None))
        self.clearInfoButtonTab3.setText(_translate("LibraryUI", "Clear", None))
        self.label_7.setText(_translate("LibraryUI", "Message", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("LibraryUI", "Borrower Management", None))
        self.label_15.setText(_translate("LibraryUI", "Message:", None))
        self.fineinfoupdateButton.setText(_translate("LibraryUI", "Fines Search", None))
        self.fineclearButton.setText(_translate("LibraryUI", "Clear", None))
        self.label_16.setText(_translate("LibraryUI", "Pay Fine Direction:", None))
        self.label_17.setText(_translate("LibraryUI", "Select Rows Left, Press Pay It!", None))
        self.finepayButton.setText(_translate("LibraryUI", "Pay It!", None))
        self.label_18.setText(_translate("LibraryUI", "Note: only instock book fine can be paid!", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("LibraryUI", "Fines", None))

